# Generated by Django 3.2.3 on 2021-05-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urldata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000)),
                ('shortcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Accessdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.CharField(blank=True, default='', max_length=200)),
                ('useragent', models.CharField(blank=True, default='', max_length=200)),
                ('ip', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=50)),
                ('shortcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.urldata')),
            ],
        ),
    ]
