# Generated by Django 3.2.3 on 2021-05-29 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urldata',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='shortcode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
