# Generated by Django 3.2.3 on 2021-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210529_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessdata',
            name='browser',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='devicefamily',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='devicetype',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='os',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='touchsupport',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
    ]
