# Generated by Django 3.2.3 on 2021-06-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210602_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessdata',
            name='location',
        ),
        migrations.AddField(
            model_name='accessdata',
            name='locationcity',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='locationcountry',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='locationregion',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
    ]
