# Generated by Django 3.2.3 on 2021-06-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210602_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessdata',
            name='lat',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='accessdata',
            name='lon',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
