# Generated by Django 3.2.3 on 2021-06-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210602_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessdata',
            old_name='shortcode',
            new_name='shorturlid',
        ),
    ]
