# Generated by Django 3.2.3 on 2021-06-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_shortcode_accessdata_shorturlid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessdata',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accessdata',
            name='lon',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
